In [1]:
import numpy as np
import pandas as pd

In [2]:
r = pd.read_csv('world_population.csv',usecols = ['2022 Population'])
max_val = r.max()
min_val = r.min()
print(max_val,min_val)

2022 Population    1425887337
dtype: int64 2022 Population    510
dtype: int64

In [3]:
wp = pd.read_csv('world_population.csv')

rowindex = wp['2022 Population'].idxmin()

country = wp['Country/Territory'][rowindex]
pop = wp['2022 Population'][rowindex]

print(country,pop)

# print(w)

Vatican City 510

find lowest rank of 10 countries

In [4]:
r = pd.read_csv('world_population.csv')

low_rank = r.sort_values(by  ='Rank', ascending= False)

low_rank[['Rank','Country/Territory']].head(10)

     Rank          Country/Territory
226   234               Vatican City
209   233                    Tokelau
150   232                       Niue
64    231           Falkland Islands
137   230                 Montserrat
177   229  Saint Pierre and Miquelon
173   228           Saint Barthelemy
216   227                     Tuvalu
229   226          Wallis and Futuna
142   225                      Nauru

In [20]:
read_file = pd.read_csv('world_population.csv')

max_val = read_file['2022 Population'].idxmax()

country = read_file['Country/Territory'][max_val]

pop = read_file['2022 Population'][max_val]



print(country,pop,max_val)

China 1425887337 41

find higest rank of 10 countries

In [30]:
high_rank = read_file.sort_values(by = 'Rank',ascending = True)

high_rank[['Rank','Country/Territory','2020 Population']].head(20)

     Rank Country/Territory  2020 Population
41      1             China       1424929781
92      2             India       1396387127
221     3     United States        335942003
93      4         Indonesia        271857970
156     5          Pakistan        227196741
149     6           Nigeria        208327405
27      7            Brazil        213196304
16      8        Bangladesh        167420951
171     9            Russia        145617329
131    10            Mexico        125998302
102    11             Japan        125244761
63     12          Ethiopia        117190911
163    13       Philippines        112190977
57     14             Egypt        107465134
55     15          DR Congo         92853164
228    16           Vietnam         96648685
94     17              Iran         87290193
213    18            Turkey         84135428
74     19           Germany         83328988
206    20          Thailand         71475664